name: yks_quiz_app
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  animate_do: ^3.0.2
  http: ^0.12.0+2
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.4

  # icons
  font_awesome_flutter: ^8.11.0
  flutter_tts: ^2.1.0
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/dersler/